"""Generated GAM noun glossary — a clear noun-phrase per command noun, consumed by
`describe.gloss()` to compose plain-English descriptions. Produced by a generate+verify pass
over the vendored grammar; regenerate on a GAM bump. Values are short lowercase noun-phrases
that read naturally after "List …" / "Show …".
"""

NOUNS = {
    "acls": "calendar sharing permissions",
    "action": "a ChromeOS device action",
    "addresses": "directory email addresses",
    "admin": "the OAuth admin account",
    "adminrole": "an admin role",
    "adminroles": "admin roles",
    "admins": "delegated admins",
    "alert": "an Alert Center alert",
    "alertfeedback": "Alert Center alert feedback",
    "alerts": "Alert Center alerts",
    "alertsettings": "Alert Center settings",
    "alias": "an email alias",
    "aliases": "email aliases",
    "analyticaccounts": "Google Analytics accounts",
    "analyticaccountsummaries": "Google Analytics account summaries",
    "analyticdatastreams": "Google Analytics data streams",
    "analyticproperties": "Google Analytics properties",
    "announcement": "a Classroom announcement",
    "apis": "Google Cloud APIs",
    "asps": "application-specific passwords",
    "backupcodes": "a user's backup verification codes",
    "browser": "a managed Chrome browser",
    "browsers": "managed Chrome browsers",
    "browsertoken": "a Chrome browser enrollment token",
    "browsertokens": "Chrome browser enrollment tokens",
    "building": "a building",
    "buildings": "resource buildings",
    "businessprofileaccounts": "a user's Business Profile accounts",
    "caalevel": "a context-aware access level",
    "caalevels": "context-aware access levels",
    "calattendees": "calendar event attendees",
    "calendar": "a calendar's sharing ACLs",
    "calendaracls": "a calendar's sharing permissions",
    "calendars": "calendars",
    "calendartrash": "a calendar's trash",
    "calsettings": "a user's calendar settings",
    "channelcustomercentitlements": "Cloud Channel customer entitlements",
    "channelcustomerentitlements": "Cloud Channel customer entitlements",
    "channelcustomers": "Cloud Channel reseller customers",
    "channeloffers": "Cloud Channel offers",
    "channelproducts": "Cloud Channel products",
    "channelskus": "Cloud Channel SKUs",
    "chat": "Google Chat bot setup",
    "chatemoji": "a user's custom Chat emoji",
    "chatemojis": "a user's custom Chat emojis",
    "chatevent": "a Google Chat event",
    "chatevents": "a user's Chat events",
    "chatmember": "a Chat space member",
    "chatmembers": "Chat space members",
    "chatmessage": "a Chat message",
    "chatmessages": "a user's Chat messages",
    "chatsearchmessages": "searched Chat messages",
    "chatsection": "a user's Chat section",
    "chatsectionitem": "a Chat space section item",
    "chatsectionitems": "items in a Chat section",
    "chatsections": "a user's Chat sections",
    "chatspace": "a Chat space",
    "chatspacedm": "a Chat direct message space",
    "chatspaces": "Google Chat spaces",
    "check": "a GAM version check",
    "chromeapp": "a Chrome, Android, or web app",
    "chromeappdevices": "devices running a Chrome app",
    "chromeapps": "Chrome apps and extensions",
    "chromeaues": "ChromeOS auto-update expiration counts",
    "chromedevicecounts": "ChromeOS device counts",
    "chromehistory": "Chrome version history",
    "chromeneedsattn": "ChromeOS devices needing attention",
    "chromenetwork": "a Chrome managed network",
    "chromepolicies": "Chrome browser policies",
    "chromepolicy": "a Chrome browser policy",
    "chromepolicyimage": "a Chrome policy image",
    "chromeprofile": "a Chrome browser profile",
    "chromeprofilecommand": "a Chrome profile remote command",
    "chromeprofilecommands": "Chrome profile remote commands",
    "chromeprofiles": "Chrome browser profiles",
    "chromeschema": "a Chrome policy schema",
    "chromeschemas": "Chrome policy schemas",
    "chromesnvalidity": "ChromeOS serial number validity",
    "chromeversions": "ChromeOS version counts",
    "chromschemas": "Chrome policy schemas",
    "cigroup": "a Cloud Identity group",
    "cigroup-members": "Cloud Identity group members",
    "cigroups": "Cloud Identity groups",
    "cimember": "a Cloud Identity group member",
    "classificationlabelpermission": "a classification label's permissions",
    "classificationlabelpermissions": "classification label permissions",
    "classificationlabels": "classification labels",
    "classroominvitation": "a Classroom invitation",
    "classroominvitations": "Classroom invitations",
    "classroomprofile": "a user's Classroom profile",
    "contact": "a domain contact",
    "contactdelegate": "a contacts delegate",
    "contactdelegates": "contacts delegates",
    "contactgroup": "a user's contact groups",
    "contactgroups": "a user's contact groups",
    "contactphotos": "domain contact photos",
    "contacts": "domain contacts",
    "count": "a count of ChromeOS devices",
    "course": "a Classroom course",
    "course-announcements": "classroom course announcements",
    "course-counts": "classroom course student/teacher counts",
    "course-materials": "classroom course materials",
    "course-participants": "classroom course participants",
    "course-studentgroup-members": "course student-group members",
    "course-studentgroupmembers": "a course student group's members",
    "course-studentgroups": "Classroom course student groups",
    "course-submissions": "classroom coursework submissions",
    "course-topics": "classroom course topics",
    "course-works": "classroom coursework items",
    "courses": "Classroom courses",
    "create": "a Google Cloud project (for GAM)",
    "cros": "ChromeOS devices",
    "crosactivity": "ChromeOS device activity",
    "crostelemetry": "ChromeOS device telemetry",
    "cseidentities": "client-side encryption identities",
    "cseidentity": "a user's CSE identity",
    "csekeypair": "a user's CSE key pair",
    "csekeypairs": "client-side encryption key pairs",
    "currentprojectid": "the current GCP project id",
    "customer": "the customer (Workspace account)",
    "customerid": "the customer ID",
    "customers": "customer usage reports",
    "datatransfer": "a data transfer",
    "datatransfers": "data transfers between users",
    "delegate": "a Gmail delegate",
    "delegates": "a user's Gmail delegates",
    "device": "a Cloud Identity device",
    "devicefile": "a ChromeOS device file",
    "devices": "Cloud Identity devices",
    "deviceuser": "a user on a managed device",
    "deviceusers": "managed device users",
    "deviceuserstate": "a device user's state",
    "diskusage": "a Drive folder's disk usage",
    "document": "a Google Docs document",
    "docuument": "a Google Docs document",
    "domain": "a domain",
    "domainalias": "a domain alias",
    "domainaliases": "domain aliases",
    "domaincontacts": "domain shared contacts",
    "domains": "domains",
    "drive": "a user's Drive content ownership",
    "driveactivity": "Drive activity events",
    "drivefile": "a user's Drive file",
    "drivefileacl": "a Drive file's sharing permissions",
    "drivefileacls": "a shared drive file's permissions",
    "drivelastmodification": "a user's last Drive modification",
    "drivesettings": "a user's Drive settings",
    "drivetrash": "a user's Drive trash",
    "emptydrivefolders": "a user's empty Drive folders",
    "event": "a calendar event",
    "events": "calendar events",
    "feature": "a resource feature",
    "features": "resource features",
    "filecomments": "a Drive file's comments",
    "filecounts": "a user's Drive file counts",
    "fileinfo": "a Drive file's metadata",
    "filelist": "a user's Drive files",
    "fileparenttree": "a Drive file's parent folder tree",
    "filepath": "a Drive file's path",
    "filerevisions": "a Drive file's revisions",
    "filesharecounts": "a user's file share counts",
    "filetree": "a user's Drive file tree",
    "filters": "a user's Gmail filters",
    "focustime": "a user's focus time event",
    "form": "a Google Form",
    "formresponses": "a Form's responses",
    "forms": "a user's Google Forms",
    "forward": "a user's Gmail forwarding",
    "forwardingaddress": "a Gmail forwarding address",
    "gcpfolder": "a Google Cloud resource folder",
    "gcporgid": "the Google Cloud organization ID",
    "gcpserviceaccount": "a GCP service account",
    "gmailprofile": "a user's Gmail profile",
    "group": "a Google group",
    "group-members": "group members",
    "groups": "groups",
    "groupslist": "a user's group memberships",
    "grouptree": "a group's membership tree",
    "guardian": "a student's guardians",
    "guardianinvitation": "a student guardian invitation",
    "imap": "a user's IMAP settings",
    "inboundssoassignment": "an inbound SSO assignment",
    "inboundssoassignments": "inbound SSO assignments",
    "inboundssocredential": "inbound SSO credentials",
    "inboundssocredentials": "inbound SSO credentials",
    "inboundssoprofile": "an inbound SSO profile",
    "inboundssoprofiles": "inbound SSO profiles",
    "instance": "the GAM customer instance",
    "isinvitable": "user invitation eligibility",
    "label": "a user's Gmail labels",
    "labelid": "a Gmail label by ID",
    "labelidlist": "Gmail labels by ID",
    "labellist": "a user's Gmail labels (in bulk)",
    "labels": "a user's Gmail labels",
    "labelsettings": "a Gmail label's settings",
    "language": "a user's display language",
    "license": "a user's product license",
    "licenses": "license assignments",
    "lookerstudioassets": "Looker Studio assets",
    "lookerstudiopermissions": "Looker Studio asset permissions",
    "meetconferences": "a user's Google Meet conferences",
    "meetparticipants": "a Meet conference's participants",
    "meetrecordings": "a Meet conference's recordings",
    "meetspace": "a user's Google Meet space",
    "meettranscripts": "a Meet conference's transcripts",
    "member": "a group member",
    "message": "a user's Gmail messages",
    "messages": "a user's Gmail messages",
    "mobile": "a mobile device",
    "note": "a user's Keep note",
    "noteacl": "a Keep note's sharing permissions",
    "noteattachments": "a Keep note's attachments",
    "notes": "a user's Google Keep notes",
    "oauth": "OAuth authorization credentials",
    "org": "an organizational unit",
    "orgs": "organizational units",
    "orgtree": "the organizational unit tree",
    "othercontacts": "a user's other contacts",
    "ou": "an organizational unit",
    "oushareddrives": "Shared Drives in an OU",
    "outofoffice": "a user's out-of-office vacation reply",
    "ownership": "a Drive file's ownership",
    "people": "people directory profiles",
    "peopleprofile": "a user's People profile",
    "permissions": "shared drive file permissions",
    "photo": "a user's profile photo",
    "policies": "Cloud Identity policies",
    "policy": "a Cloud Identity policy",
    "pop": "a user's POP settings",
    "print": "data transfer apps",
    "printer": "a managed printer",
    "printermodels": "supported printer models",
    "printers": "managed printers",
    "privileges": "admin role privileges",
    "profile": "a user's directory profile",
    "profilephoto": "a user's profile photo",
    "project": "a Google Cloud project",
    "projects": "Google Cloud projects",
    "recipient": "email recipients",
    "resetpvi": "a YubiKey PIV reset",
    "resoldcustomer": "a reseller customer",
    "resoldsubscription": "a reseller customer subscription",
    "resoldsubscriptions": "reseller subscriptions",
    "resource": "a resource calendar",
    "resources": "calendar resources",
    "sakey": "a service account key",
    "sakeys": "service account keys",
    "schema": "a custom user schema",
    "schemas": "custom user schemas",
    "sendas": "Gmail send-as addresses",
    "serviceaccount": "a service account's OAuth scopes",
    "settings": "a calendar's settings",
    "shareddrive": "a shared drive",
    "shareddriveacls": "a shared drive's permissions",
    "shareddriveinfo": "a shared drive's details",
    "shareddriveorganizers": "Shared Drive organizers",
    "shareddrives": "shared drives",
    "shareddrivethemes": "shared drive themes",
    "sheet": "a Google Sheets spreadsheet",
    "sheetrange": "a Google Sheets cell range",
    "signature": "a user's Gmail signature",
    "smime": "a user's S/MIME certificate",
    "smimes": "a user's S/MIME certificates",
    "storagebucket": "a Takeout storage bucket",
    "storagefile": "a Cloud Storage file",
    "students": "students in a Classroom course",
    "suspended": "a user's suspended status",
    "svcacct": "a GAM service account",
    "svcaccts": "Google Cloud service accounts",
    "tagmanageraccounts": "Google Tag Manager accounts",
    "tagmanagerccounts": "Google Tag Manager accounts",
    "tagmanagercontainers": "a user's Tag Manager containers",
    "tagmanagerpermissions": "Tag Manager account permissions",
    "tagmanagertags": "Tag Manager tags in a workspace",
    "tagmanagerworkspaces": "a user's Tag Manager workspaces",
    "task": "a user's task",
    "tasklist": "a user's task list",
    "tasklists": "a user's task lists",
    "tasks": "a user's Google Tasks",
    "teachers": "a course's teachers",
    "todrive": "CSV output uploaded to Drive",
    "tokens": "a user's OAuth app tokens",
    "topic": "a Classroom course topic",
    "usage": "usage reports",
    "usageparameters": "report usage parameters",
    "user": "a user account",
    "usercountsbyorgunit": "user counts by org unit",
    "userinvitation": "a Cloud Identity user invitation",
    "userinvitations": "Cloud Identity user invitations",
    "userlist": "a list of users",
    "users": "users' activity reports",
    "vacation": "a user's vacation auto-reply",
    "vaultcounts": "Vault retained item counts",
    "vaultexport": "Vault (eDiscovery) exports",
    "vaultexports": "Vault (eDiscovery) exports",
    "vaulthold": "a Vault legal hold",
    "vaultholds": "Vault legal holds",
    "vaultmatter": "a Vault (eDiscovery) matter",
    "vaultmatters": "Vault (eDiscovery) matters",
    "vaultqueries": "Vault (eDiscovery) saved queries",
    "vaultquery": "a Vault search query",
    "verify": "domain verification records",
    "webmastersites": "Search Console sites",
    "webresources": "Search Console web resources",
    "workinglocation": "a user's working location",
    "youtubechannels": "a user's YouTube channels",
}
